# Generated by Django 3.2.6 on 2022-02-15 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('post_data', models.TextField()),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('post_date', models.DateField(default=datetime.datetime(2022, 2, 15, 23, 29, 9, 703744))),
            ],
        ),
    ]
