# Generated by Django 3.2.6 on 2022-02-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 15, 23, 32, 8, 246358)),
        ),
    ]
